tags:
  - name: Input kalimat
del :
  description: Teks yang akan diproses
parameters:
  - name: input_teks
    in: formData
    required: true
    type: string
responses:
    '200':
      description: Successful response
    '400':
      description: Bad Request
    '500':
      description: Internal Server Error